### ISSUE TITLE
Возникла проблема, при запуске проекта

### ISSUE THREAD

**Issue by aldabergenovb** [kant2002/NKalkan#1]
![image](https://user-images.githubusercontent.com/46986022/230280173-d5d65cce-4da4-46de-9cce-78e7c6fe4987.png)
System.TypeInitializationException: "The type initializer for 'NKalkan.KalkanApi' threw an exception."

EntryPointNotFoundException: Unable to find an entry point named 'KC_GetFunctionList' in DLL 'KalkanCryptCOM'.

Положил файл dll из SDK 
![image](https://user-images.githubusercontent.com/46986022/230280325-f8306651-5080-407f-b102-4a1ddad64b53.png)
тут изменил названия на KalkanCryptCOM т.к. dll так называется из SDK

**Comment by kant2002** [comment]
В данной библиотеке не используется COM версия, так как я хочу кросс-платтформенности. Поищите пожалуйста файл `KalkanCrypt_x64.dll` примерно тут `SDK 2.0\C\Windows\KalkanCrypt\lib`

**Comment by aldabergenovb** [comment]
> В данной библиотеке не используется COM версия, так как я хочу кросс-платтформенности. Поищите пожалуйста файл `KalkanCrypt_x64.dll` примерно тут `SDK 2.0\C\Windows\KalkanCrypt\lib`

Спасибо, помогло :)

**Comment by aldabergenovb** [comment]
Еще вопрос будет ли реализация, чтобы не указывать путь до эцп ключа, а передавать его в base64 как в ncanode? Бывают моменты когда ЭЦП для подписи не охотно дают
Т.е. чтобы физический ключ не хранить на самом сервере

**Comment by kant2002** [comment]
Звучит логично. попробуйте обновить версию до 0.1.1, и я в README пример добавил.

**Comment by kant2002** [comment]
Если есть еще пожелания, откройте новую задачу. А пока, раз изначальная проблема решена я закрою
