### ISSUE TITLE
Метод GetCertFromXML

### ISSUE THREAD

**Issue by Kyrmasch** [kant2002/NKalkan#4]
Спасибо за предоставленную библиотеку для работы с Kalkan - очень выручила, т.к были сложности с работой в .NET под Linux. Если будет возможно - можно ли включить метод GetCertFromXML и X509ValidateCertificate в данную библиотеку? Заранее спасибо! 

Пример кода:

`kalkanCom.GetCertFromXML(xml, 1, out string cert);
 var ocspUrl = "http://ocsp.pki.gov.kz/";
 kalkanCom.X509ValidateCertificate(
                cert,
                (int)KALKANCRYPTCOM_VALIDTYPE.KC_USE_OCSP,
                ocspUrl,
                DateTime.Now,
                out string validate,
                (int)KALKANCRYPTCOM_FLAGS.KC_GET_OCSP_RESPONSE,
                out string responce
            );
 uint result = kalkanCom.GetLastError(out string error);
 return result;`

**Comment by kant2002** [comment]
I add `ValidateCertificate` and convinience method `ValidateCertificateOscp` with less parameters. Also `GetCertificateFromXml` and `GetSignatureAlgrithmFromXml` added.

Check for NKalkan 0.4.0
